version: '3.7'

services:
  web:
    build: ./todo-backend/backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: front:latest
    build: ./todo-frontend/frontend
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
